[dependency-groups]
dev = [
    "alembic>=1.17.2",
    "faker>=38.2.0",
    "fastapi>=0.121.3",
    "passlib>=1.7.4",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "sqladmin[full]>=0.21.0",
    "sqlalchemy>=2.0.44",
    "sqlalchemy-utils>=0.42.0",
    "unicorm>=0.0.2",
    "uvicorn[standard]>=0.38.0",
]
